-- The repository's laws, measured over the files git tracks (plus any untracked file not ignored), for
-- .robot/rules.robot. tablua/ is a submodule with its own laws and is never walked.
--
--   laws.limit                   400: the most lines a code or Robot file may have
--   laws.counts(path) -> bool    whether the limit applies (code, Robot and config; data and media do not)
--   laws.library(root) -> robot library
local robot = require("robot")

local M = {}

M.limit = 400

-- the limit is for what people and models read and write; data (fixtures, goldens, locks) is exempt
M.code = { lua = true, rs = true, robot = true, sh = true, toml = true, swift = true, wgsl = true, glsl = true,
  frag = true, vert = true, js = true, ts = true, tsx = true, mjs = true, py = true, html = true, css = true }
M.exempt = { ["AGENTS.md"] = "the bet and how to work here, read whole by every agent (owner, 2026-10-07)",
  ["native/Cargo.lock"] = "generated by cargo", ["editor/src-tauri/Cargo.lock"] = "generated by cargo" }

function M.counts(path)
  if M.exempt[path] then return false end
  local ext = path:match("%.([%w]+)$")
  if ext then return M.code[ext] == true end
  return path == "moonsplice"
end

local function q(s) return "'" .. tostring(s):gsub("'", "'\\''") .. "'" end

local function files(root)
  local p = assert(io.popen(("git -C %s ls-files --cached --others --exclude-standard"):format(q(root))))
  local out = {}
  for l in p:lines() do if l ~= "tablua" and not l:match("^tablua/") then out[#out + 1] = l end end
  p:close()
  return out
end

local function line_count(path)
  local f = io.open(path, "rb")
  if not f then return 0 end
  local s = f:read("*a"); f:close()
  local n = select(2, s:gsub("\n", ""))
  if #s > 0 and s:sub(-1) ~= "\n" then n = n + 1 end
  return n
end

local function list_or_pass(bad, what)
  if #bad == 0 then return end
  table.sort(bad)
  error(("%d %s:\n  %s"):format(#bad, what, table.concat(bad, "\n  ", 1, math.min(#bad, 60))), 0)
end

function M.library(root)
  local lib = robot.library()
  local tree

  local function all() tree = tree or files(root); return tree end

  lib:add("Use Tree", function(path)
    if path and path ~= "" then root = path end
    tree = nil
    return #all()
  end)

  lib:add("Every File Is Within The Limit", function()
    local bad = {}
    for _, p in ipairs(all()) do
      if M.counts(p) then
        local n = line_count(root .. "/" .. p)
        if n > M.limit then bad[#bad + 1] = ("%s: %d lines"):format(p, n) end
      end
    end
    list_or_pass(bad, "files over " .. M.limit .. " lines")
  end)

  lib:add("No Markdown", function()
    local bad = {}
    -- AGENTS.md is the one exception: the file every agent reads first, and CLAUDE.md is a link to it. README.md
    -- is GitHub's front page for people (owner, 2026-10-07): it introduces and links, and documents nothing
    local linked = { ["CLAUDE.md"] = true }
    for _, p in ipairs(all()) do
      local md = p:lower():match("%.md$") or p:lower():match("%.markdown$")
      if md and p ~= "AGENTS.md" and p ~= "README.md" then
        local h = linked[p] and io.popen("readlink " .. root .. "/" .. p)
        local to = h and h:read("*l"); if h then h:close() end
        if to ~= "AGENTS.md" then bad[#bad + 1] = p end
      end
    end
    list_or_pass(bad, "markdown files (documentation is Robot, in .robot/; AGENTS.md is the one exception)")
  end)

  lib:add("Root Holds Only", function(...)
    local allowed = {}
    for _, name in ipairs({ ... }) do allowed[name] = true end
    local bad, seen = {}, {}
    for _, p in ipairs(all()) do
      local top = p:match("^([^/]+)")
      if not allowed[top] and not seen[top] then seen[top] = true; bad[#bad + 1] = top end
    end
    list_or_pass(bad, "entries at the root outside the allowed set")
  end)

  lib:add("Robot Lives In .robot", function()
    local bad = {}
    for _, p in ipairs(all()) do if p:match("%.robot$") and not p:match("^%.robot/") then bad[#bad + 1] = p end end
    list_or_pass(bad, ".robot files outside .robot/")
  end)

  -- core/ and .robot/ only: native/ follows cargo's layout; comps/, assets/ and .robot/runs keep their media's folders
  lib:add("Folders Are At Most ${n} Deep", function(n)
    n = tonumber(n)
    local bad = {}
    for _, p in ipairs(all()) do
      local _, depth = p:gsub("/", "")
      local own = p:match("^core/") or (p:match("^%.robot/") and not p:match("^%.robot/runs/"))
      if depth > n and own then bad[#bad + 1] = p end
    end
    list_or_pass(bad, "files deeper than " .. n .. " folders")
  end)

  -- Lua's share of the lines of code (lua, rs, sh, swift, wgsl, py, js, ts); Robot is documentation and tests.
  -- editor/ is the desktop app (Tauri + React), counted apart: the engine and its comps are what must be Lua
  lib:add("Lua Share Of Code", function()
    local lua, total = 0, 0
    for _, p in ipairs(all()) do
      local ext = p:match("%.([%w]+)$")
      if ext and M.code[ext] and ext ~= "robot" and ext ~= "toml" and ext ~= "html" and ext ~= "css"
        and not p:match("^editor/") then
        local n = line_count(root .. "/" .. p)
        total = total + n
        if ext == "lua" then lua = lua + n end
      end
    end
    local share = total > 0 and lua / total or 1
    print(("  Lua %d of %d lines of code (%.0f%%)"):format(lua, total, share * 100))
    return share
  end)

  -- a command run from the checkout (or a folder in it); its last lines are the failure message
  lib:add("Command Succeeds", function(cmd, dir)
    local where = dir and dir ~= "" and (root .. "/" .. dir) or root
    local p = assert(io.popen(("cd %s && %s 2>&1; echo \"@rc $?\""):format(q(where), cmd)))
    local s = p:read("*a"); p:close()
    local out, code = s:match("^(.-)@rc (%d+)%s*$")
    if tonumber(code) ~= 0 then error(("%s exited %s:\n%s"):format(cmd, code, (out or s):sub(-1500)), 0) end
  end)

  lib:add("Path Exists", function(path)
    local f = io.open(root .. "/" .. path)
    if not f then error(path .. " does not exist", 0) end
    f:close()
  end)

  return lib
end

return M
